openapi: 3.0.1
info:
  title: qg_api_t
  description: qualys guard rest api
  version: 1.0.0

servers:
- url: http://localhost:2010/v1
tags:
- name: admin
  description: amin actions
- name: scan
- name: report
  description: report related action
- name: vulner
  description: vulnerabilities reelated actions
- name: patch
  description: patch related actions
paths:
  /scan:
    post:
      tags:
      - scan
      summary: Create scan
      description: Create scan
      operationId: create_scan
      requestBody:
        description: Scan data to be created
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Scan'
      responses:
        default:
          description: successful operation
          content: {}
      x-openapi-router-controller: qg_api.api

  /scan/{scan_id}:
    get:
      tags:
      - scan
      summary: Get user by id
      description: Get user by id - description
      operationId: get_scan
      parameters:
      - name: scan_id
        in: path
        description: ID of scan
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: successfull operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Scan'
      x-openapi-router-controller: qg_api.api

  /report:
    post:
      tags:
      - report
      summary: Create report
      description: Create Report
      operationId: create_report
      requestBody:
        description: Data for report genration
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Report'
      responses:
        200:
          description: successfull operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                  status:
                    type: string
        default:
          description: successfull operation
          content: {}
      x-openapi-router-controller: qg_api.api
  /report/{report_id}:
    get:
      tags:
      - report
      summary: Get report by id
      description: Get report by id - description
      operationId: get_report
      parameters:
      - name: report_id
        in: path
        description: ID of scan
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: successfull operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Report'
      x-openapi-router-controller: qg_api.api

  /admin/{action}:
    get:
      tags:
      - admin
      summary: for admin actions
      description: for admin actions
      operationId: admin_action
      parameters:
      - name: action
        in: path
        description: action to perform
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        200:
          description: successfull operation
      x-openapi-router-controller: qg_api.api

components:
  schemas:
    Server:
      type: object
      properties:
        ip:
          type: string
      example:
        ip: ip

    ServerFindings:
      type: object
      additionalProperties:
          type: object
          properties:
            vulners:
              type: array
              items:
                $ref: '#/components/schemas/Vulner'
            patches:
              type: array
              items:
                $ref: '#/components/schemas/Patch'

    Scan:
      type: object
      properties:
        id:
          type: integer
          format: int64
        status:
          type: string
        title:
          type: string
        launched:
          type: string
          format: date-time
        servers:
          type: array
          items:
            $ref: '#/components/schemas/Server'
      example:
        servers:
        - ip: ip
        - ip: ip
        id: 0
        title: title
        launched: 2000-01-23T04:56:07.000+00:00
        status: status
    Report:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        status:
          type: string
        launched:
          type: string
          format: date-time
        servers:
          type: array
          items:
            $ref: '#/components/schemas/ServerFindings'

    Vulner:
      type: object
      properties:
        qid:
          type: integer
          format: int64
        patch_qid:
          type: integer
          format: int64
        severity:
          type: string
        title:
          type: string
        category:
          type: integer
          format: int64
      example:
        severity: severity
        solution: solution
        cveid: 5
        title: title
        category: 5
        qid: 6
        patch_qid: 1
    Patch:
      type: object
      properties:
        qid:
          type: integer
          format: int64
        severity:
          type: integer
          format: int64
        title:
          type: string
        vulners:
          type: array
          items:
            $ref: '#/components/schemas/Vulner'
      example:
        severity: 7
        title: title
        qid: 2
        vulners:
        - null
        - null
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: query
      x-apikeyInfoFunc: qg_api.api.apikey_auth
    basic_http:
      type: http
      scheme: basic
      x-basicInfoFunc: qg_api.api.basic_auth
