version: '3.2'

services:
  swagger-editor:
    image: swaggerapi/swagger-editor
    ports:
      - "888:8080"

  mysql_qualys_guard:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      -  "3309:3306"
    environment:
        MYSQL_DATABASE: qualys_guard
        MYSQL_ROOT_PASSWORD: 123456
    volumes:
      -  mysql_qualys_guard:/var/lib/mysql

  qualys_guard:
    build: ..
    ports:
      - "2010:8080"
    depends_on:
      - mysql_qualys_guard

volumes:
  mysql_qualys_guard:
